version: "3.7"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
  
    volumes:
      - /root/docker/jellyfin/config:/config
      - /root/docker/jellyfin/data/tvshows:/data/tvshows
      - /root/docker/jellyfin/data/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - jellyfin
    restart: unless-stopped

  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /root/docker/sonarr/config:/config
      - /root/docker/sonarr/tv:/tv #optional
      - /root/docker/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    networks:
      - jellyfin
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /root/docker/radarr/config:/config
      - /root/docker/radarr/movies:/movies #optional
      - /root/docker/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    networks:
      - jellyfin
    restart: unless-stopped

networks:
  jellyfin
